"""
Prompt Builder

Responsible for creating prompts sent to the LLM.

This module contains no API calls.

The prompt is completely dataset-agnostic and uses the
metadata generated by file_service.py.
"""

from typing import Any


# ============================================================
# Format Column
# ============================================================

def _format_column(
    column: dict[str, Any],
) -> str:
    """
    Format a column's metadata for the SQL-generation prompt.

    The column metadata may contain:

        - name
        - datatype
        - total_values
        - missing_count
        - unique_count
        - unique_values

    unique_values are already limited by file_service.py
    using MAX_UNIQUE_VALUES_FOR_METADATA.

    Therefore, this function does NOT apply another arbitrary
    value limit.
    """

    name = column.get(
        "name",
        "",
    )

    datatype = column.get(
        "datatype",
        "unknown",
    )

    total_values = column.get(
        "total_values"
    )

    missing_count = column.get(
        "missing_count"
    )

    unique_count = column.get(
        "unique_count"
    )

    parts = [
        f"- {name} ({datatype})"
    ]

    # --------------------------------------------------------
    # Basic statistics
    # --------------------------------------------------------

    if total_values is not None:

        parts.append(
            f"  Total rows: {total_values}"
        )

    if missing_count is not None:

        parts.append(
            f"  Missing values: {missing_count}"
        )

    if unique_count is not None:

        parts.append(
            f"  Unique values: {unique_count}"
        )

    # --------------------------------------------------------
    # Observed categorical values
    # --------------------------------------------------------
    #
    # file_service.py already applies the global threshold:
    #
    # MAX_UNIQUE_VALUES_FOR_METADATA = 50
    #
    # Therefore DO NOT do:
    #
    # values = values[:30]
    #
    # here.
    #
    # --------------------------------------------------------

    values = column.get(
        "unique_values"
    )

    if values:

        formatted_values = ", ".join(
            repr(str(value))
            for value in values
        )

        parts.append(
            f"  Observed values: {formatted_values}"
        )

    return "\n".join(parts)


# ============================================================
# Build SQL Prompt
# ============================================================

def build_sql_prompt(
    question: str,
    columns: list[dict[str, Any]],
    schema_context: str | None = None,
) -> str:
    """
    Build a dataset-agnostic prompt for SQL generation.

    The LLM receives:
        - column names
        - datatypes
        - missing-value information
        - unique-value information
        - observed categorical values when available
        - optional retrieved semantic context
    """

    # --------------------------------------------------------
    # Format complete schema
    # --------------------------------------------------------

    if not columns:

        schema = "NO SCHEMA INFORMATION AVAILABLE"

    else:

        schema = "\n".join(
            _format_column(column)
            for column in columns
        )

    # --------------------------------------------------------
    # Prompt
    # --------------------------------------------------------

    retrieved_block = ""
    if schema_context:
        retrieved_block = f"{schema_context}\n"

    prompt = f"""
You are an expert SQLite SQL query generator.

Your job is to translate the user's natural-language question
into ONE accurate, executable SQLite SQL query.

The database table contains the COMPLETE uploaded dataset.

==================================================
DATASET SCHEMA
==================================================

{schema}

{retrieved_block}==================================================
TABLE
==================================================

The table name is exactly:

dataset

==================================================
USER QUESTION
==================================================

{question}

==================================================
IMPORTANT SEMANTIC PRINCIPLES
==================================================

The database is the source of truth for the actual data.

The schema and observed values provided above are context that
helps you correctly understand the meaning of the columns.

You must generate SQL that operates on the COMPLETE dataset.

Do not answer from the schema metadata alone.

==================================================
STRICT SQL GENERATION RULES
==================================================

1. Return ONLY ONE valid SQLite SQL query.

2. Do NOT explain the query.

3. Do NOT use Markdown.

4. Do NOT wrap the SQL inside code fences.

5. Use ONLY columns that appear in the provided schema.

6. NEVER invent a column name.

7. The table name is exactly "dataset".

8. Inspect the observed values provided for a column before
   deciding how categorical data should be interpreted.

9. NEVER assume that:

       IS NOT NULL

   means that a condition, event, status, or category is
   positively present.

10. NULL means missing or unknown data.

    NULL does NOT automatically mean:
        - No
        - Yes
        - False
        - Zero

11. NULL comparisons MUST use:

       IS NULL
       IS NOT NULL

    Never use:

       = NULL
       != NULL
       <> NULL

12. If a categorical column contains an affirmative and a
    negative category, distinguish them when answering
    positive-occurrence questions.

    Example:

       "Yes"
       "No"

    A question asking how many records have the condition
    should normally count the affirmative category rather than
    simply counting all non-NULL records.

13. Do NOT count a negative category such as "No" as a positive
    occurrence unless the user explicitly asks for the negative
    category.

14. If the user explicitly asks for the negative category,
    count that category normally.

15. Use ACTUAL observed categorical values from the schema when
    they are available.

16. NEVER invent categorical values.

17. If values differ only by capitalization or surrounding
    whitespace and the user is asking for a case-insensitive
    categorical match, use appropriate normalization such as:

       LOWER(TRIM(column))

18. When filtering text values, use the actual values observed
    in the dataset whenever those values are available.

19. Do not assume that every non-empty value represents a
    positive response.

20. Do not assume that every non-NULL value represents a
    positive response.

21. For questions asking:

       how many
       count
       percentage
       average
       minimum
       maximum
       distribution
       proportion
       overall
       most common
       least common

    perform the requested calculation over the COMPLETE
    dataset unless the user explicitly specifies a subset.

22. Do NOT add LIMIT to aggregate or dataset-wide analytical
    queries.

23. Use LIMIT ONLY when the user explicitly asks for:

       - a sample
       - first N rows
       - last N rows
       - N records
       - N examples
       - a limited number of results

24. Never use the 10-row or preview data to answer a
    dataset-wide question.

25. The dataset preview is NOT the complete dataset.

26. For COUNT questions, use an appropriate COUNT expression.

27. For average questions, use AVG().

28. For minimum questions, use MIN().

29. For maximum questions, use MAX().

30. For sum questions, use SUM().

31. For distribution questions, use GROUP BY with an
    appropriate aggregate.

32. For percentage questions, calculate the requested
    numerator and denominator from the relevant dataset rows.

33. For "most common" or "least common" questions, use
    GROUP BY and COUNT(), followed by the appropriate ordering.

34. Do not introduce a LIMIT merely because the result could
    contain many categories.

35. Do not confuse a column's existence with a condition being
    present.

36. Do not confuse missing values with negative responses.

37. Do not confuse empty strings with positive responses.

38. If the user asks about a specific value that is not listed
    in the observed-value metadata, it may still be queried
    against the complete dataset.

    The observed-value list is contextual information, NOT a
    restriction on what SQL may query.

39. The unique-value metadata threshold is ONLY an LLM context
    optimization.

    It does NOT limit:
       - the dataset
       - the rows
       - the values
       - SQL execution
       - GROUP BY
       - filtering
       - aggregation

40. If a column has more unique values than the metadata
    threshold, the SQL query can still operate on any value
    stored in that column.

==================================================
SEMANTIC CATEGORICAL QUESTIONS
==================================================

When the user asks questions such as:

- How many reported X?
- How many have X?
- How many completed X?
- How many are active?
- How many were cancelled?
- How many passed?
- How many failed?
- How many are present?
- How many selected X?

inspect the actual observed values of the relevant column.

If the column contains categories such as:

    Yes
    No

then a positive-occurrence question should normally count
the affirmative category.

If the column contains categories such as:

    Completed
    Pending
    Cancelled

then a question asking how many completed something should
filter for "Completed".

If the column contains multiple affirmative categories,
use the categories that are actually relevant to the user's
question.

Do NOT assume that one universal value such as "Yes" exists
for every dataset.

==================================================
INSUFFICIENT SCHEMA RULE
==================================================

The fallback query:

SELECT 'INSUFFICIENT_SCHEMA';

MUST ONLY be returned when the question genuinely cannot be
answered using the provided schema.

Return INSUFFICIENT_SCHEMA ONLY when:

1. The question requires a column that does NOT exist in the
   provided schema,

OR

2. The requested calculation is mathematically impossible
   using the available columns.

DO NOT return INSUFFICIENT_SCHEMA merely because:

- the question requires interpreting categorical values,
- a column has more than 50 unique values,
- a specific value is not included in the observed-value list,
- the dataset contains NULL values,
- the column has missing values,
- the question requires filtering,
- the question requires GROUP BY,
- the question requires COUNT,
- the question requires percentage calculation,
- the semantic meaning is not explicitly written in the
  column name.

If a relevant column exists and the question can reasonably
be answered using that column and the actual dataset, generate
the SQL query.

==================================================
EXAMPLE OF CORRECT REASONING
==================================================

Suppose the schema contains:

- Status (object)
  Observed values: 'Yes', 'No'

Question:

How many records have the status?

The query should use the observed categorical values to
determine an appropriate positive/affirmative interpretation.

Do NOT return:

SELECT 'INSUFFICIENT_SCHEMA';

==================================================
IMPORTANT EXAMPLE
==================================================

Suppose the schema contains:

- Response (object)
  Observed values: 'Yes', 'No'

Question:

How many respondents reported the condition?

The presence of the Response column means the question is
potentially answerable.

Do NOT return INSUFFICIENT_SCHEMA merely because the phrase
"reported the condition" is semantic.

Inspect the observed values and construct an appropriate
categorical filter.

==================================================
FULL-DATASET REQUIREMENT
==================================================

The uploaded dataset may contain many more rows than the
preview shown to the user.

Always perform analytical queries against the complete
"dataset" table.

Never answer a dataset-wide question using only preview rows.

==================================================
SQL SAFETY
==================================================

The generated query MUST:

- be valid SQLite syntax,
- use the exact table name "dataset",
- reference only available columns,
- use correct NULL semantics,
- use actual observed categorical values when available,
- avoid invented values,
- avoid invented columns,
- avoid unnecessary LIMIT clauses,
- operate on the complete dataset.

==================================================
FINAL CHECK BEFORE RETURNING SQL
==================================================

Before returning the SQL, verify:

1. Does every referenced column exist?

2. Does the query answer the exact user question?

3. If a categorical condition is involved, did you inspect the
   observed values?

4. Did you avoid treating IS NOT NULL as proof of a positive
   condition?

5. Did you handle NULL correctly?

6. Did you avoid treating a negative category as positive?

7. Is the query operating over the complete dataset?

8. Did you avoid LIMIT unless explicitly requested?

9. Is every categorical value used in the SQL either:
   - observed in the provided metadata, or
   - explicitly supplied by the user?

10. Is the SQL valid SQLite?

11. Is INSUFFICIENT_SCHEMA truly necessary?

If the question can be answered, NEVER return:

SELECT 'INSUFFICIENT_SCHEMA';

Return ONLY the SQL query.
"""

    return prompt.strip()


def build_sql_regeneration_prompt(
    question: str,
    columns: list[dict],
    previous_sql: str,
    errors: list[str],
    schema_context: str | None = None,
) -> str:
    """
    Build a prompt instructing the LLM to correct its previous SQL query based on validation errors.
    """
    base_prompt = build_sql_prompt(question=question, columns=columns, schema_context=schema_context)
    
    errors_str = "\n".join(f"- {err}" for err in errors)
    
    feedback = f"""
==================================================
PREVIOUS ATTEMPT AND VALIDATION ERRORS
==================================================

On the previous attempt, you generated the following SQL:
```sql
{previous_sql}
```

However, this query failed validation with the following error(s):
{errors_str}

Please correct the SQL query to solve all the validation errors listed above. Make sure:
1. Every column referenced actually exists in the schema.
2. The table name is strictly "dataset" (or matching the SQLite schema).
3. The SQL is valid SQLite syntax.
4. You do not introduce any write/modification commands.

Return ONLY the corrected SQL query. Do not include any explanations or markdown wrapping.
"""
    return base_prompt + "\n" + feedback